version: '3.7'
services:
  eventshuffle:
    image: dmonteroh/eventshuffle_poc
    restart: always
    build: .
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    links:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: