version: '3.7'
services:
  eventshuffle:
    image: dmonteroh/eventshuffle_poc
    restart: always
    build: .
    ports:
      - 8080:8080
    links:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: